[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = "fd -t f . ~/.config -H -E *Cache* -E Default"

[preview]
command = "cat {}"
