[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat"]

[source]
command = ["fd -t f --absolute-path . /home/dnk/.config -E *Cache* -E Slack -E Bitwarden"]

[preview]
command = "bat -n --color=always '{}'"
env = { BAT_THEME = "ansi" }
